// ============================================================
// FILE: backend/seedPracticeQuestions.js
// HOW TO RUN: node seedPracticeQuestions.js
// This seeds the Practice Quiz questions into MongoDB
// ============================================================

const mongoose = require("mongoose");
require("dotenv").config({ path: require("path").join(__dirname, "..", ".env") });

const connectDB = async () => {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log("✅ MongoDB Connected");
};

// Reuse your existing Question model schema
const questionSchema = new mongoose.Schema({
  subject: String,
  topic: String,
  question: String,
  options: [String],
  correctAnswer: Number, // 0-indexed
  type: { type: String, default: "practice" }, // "practice" | "teacher"
  difficulty: { type: String, default: "medium" },
}, { timestamps: true });

const Question = mongoose.models.Question || mongoose.model("Question", questionSchema);

// ============================================================
// SUBJECTS & TOPICS
// ============================================================
// Subject 1: English
// Topic 1: Grammar & Parts of Speech
// Topic 2: Essay Writing & Composition
// Topic 3: Reading Comprehension

// Subject 2: Introduction to Programming
// Topic 1: Basics of C++ / Programming Fundamentals
// Topic 2: Control Structures & Loops
// Topic 3: Functions & Arrays

// Subject 3: Digital Logic Design (DLD)
// Topic 1: Number Systems & Boolean Algebra
// Topic 2: Logic Gates & Combinational Circuits
// Topic 3: Sequential Circuits & Flip-Flops

// Subject 4: Data Structures
// Topic 1: Arrays, Linked Lists & Stacks
// Topic 2: Queues, Trees & Binary Search Trees
// Topic 3: Sorting & Searching Algorithms

// Subject 5: Calculus
// Topic 1: Limits & Continuity
// Topic 2: Differentiation
// Topic 3: Integration
// ============================================================

const practiceQuestions = [

  // ============================================================
  // SUBJECT: English
  // ============================================================

  // --- Topic: Grammar & Parts of Speech ---
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Which of the following is a proper noun?",
    options: ["city", "river", "London", "mountain"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Identify the verb in the sentence: 'She quickly ran to the store.'",
    options: ["She", "quickly", "ran", "store"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Which sentence is grammatically correct?",
    options: [
      "He don't know the answer.",
      "She doesn't knows the answer.",
      "They doesn't know the answer.",
      "He doesn't know the answer.",
    ],
    correctAnswer: 3,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "What part of speech is the word 'beautiful' in 'She wore a beautiful dress'?",
    options: ["Noun", "Adverb", "Adjective", "Verb"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Which word is an adverb in: 'He spoke loudly in the hall'?",
    options: ["He", "spoke", "loudly", "hall"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "A pronoun is used to:",
    options: [
      "Describe a noun",
      "Replace a noun",
      "Connect two clauses",
      "Express action",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Which is a collective noun?",
    options: ["Happiness", "Flock", "Running", "Beautiful"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "What type of sentence is: 'Close the door!'?",
    options: ["Declarative", "Interrogative", "Exclamatory", "Imperative"],
    correctAnswer: 3,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Which conjunction is used to show contrast?",
    options: ["and", "because", "but", "so"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "The plural of 'child' is:",
    options: ["childs", "childes", "children", "childrens"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Which article is used before a vowel sound?",
    options: ["a", "an", "the", "both a and the"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "In 'The cat sat on the mat', the preposition is:",
    options: ["The", "cat", "sat", "on"],
    correctAnswer: 3,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Which sentence uses the past perfect tense?",
    options: [
      "She is eating.",
      "She had eaten before he arrived.",
      "She ate lunch.",
      "She will eat later.",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "An interjection expresses:",
    options: ["Action", "Description", "Strong emotion", "Relation between nouns"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Which sentence is in passive voice?",
    options: [
      "Ali wrote the letter.",
      "The letter was written by Ali.",
      "Ali is writing the letter.",
      "Ali had written the letter.",
    ],
    correctAnswer: 1,
    type: "practice",
  },

  // --- Topic: Essay Writing & Composition ---
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "What is the main purpose of an introductory paragraph in an essay?",
    options: [
      "To provide evidence",
      "To summarize the essay",
      "To present the thesis and hook the reader",
      "To list all arguments",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "A thesis statement is best described as:",
    options: [
      "A question about the topic",
      "The central argument of the essay",
      "A list of facts",
      "The conclusion of the essay",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "Which paragraph type presents facts to support the main argument?",
    options: ["Introduction", "Body paragraph", "Conclusion", "Hook paragraph"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "What does 'coherence' mean in essay writing?",
    options: [
      "Using difficult vocabulary",
      "Ideas flowing logically and smoothly",
      "Writing long sentences",
      "Using many examples",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "A persuasive essay aims to:",
    options: [
      "Entertain the reader",
      "Describe a place",
      "Convince the reader of a viewpoint",
      "Narrate a story",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "Which transitional phrase introduces a contrasting idea?",
    options: ["Furthermore", "In addition", "However", "As a result"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "The concluding paragraph of an essay should:",
    options: [
      "Introduce a new argument",
      "Restate the thesis and summarize key points",
      "Ask a question",
      "List all the evidence used",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "Which essay type tells about personal experience?",
    options: ["Argumentative", "Expository", "Narrative", "Descriptive"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "Plagiarism in academic writing means:",
    options: [
      "Writing too many paragraphs",
      "Using someone else's work without credit",
      "Writing in a formal tone",
      "Using transitional phrases",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "Which of these is NOT a prewriting strategy?",
    options: ["Brainstorming", "Outlining", "Proofreading", "Mind mapping"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "The audience in writing refers to:",
    options: [
      "The writer's purpose",
      "The people who will read the writing",
      "The topic of the essay",
      "The length of the essay",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "In formal academic writing, contractions like 'don't' should be:",
    options: ["Used frequently", "Used only in conclusions", "Avoided", "Used in introductions only"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "A 'hook' in the introduction is meant to:",
    options: [
      "Define the topic",
      "List evidence",
      "Grab the reader's attention",
      "State the conclusion",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "Revising an essay involves:",
    options: [
      "Checking spelling errors only",
      "Improving content, structure, and clarity",
      "Adding more words to meet word count",
      "Writing a new essay",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "An expository essay is written to:",
    options: [
      "Argue a position",
      "Tell a story",
      "Explain or inform about a topic",
      "Describe feelings",
    ],
    correctAnswer: 2,
    type: "practice",
  },

  // --- Topic: Reading Comprehension ---
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "The main idea of a passage is:",
    options: [
      "A minor detail in the text",
      "The central point the author wants to convey",
      "The first sentence of the paragraph",
      "A supporting example",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "Inference in reading means:",
    options: [
      "Reading the text aloud",
      "Finding a word in the dictionary",
      "Drawing a conclusion not directly stated",
      "Summarizing the passage",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "The tone of a passage refers to:",
    options: [
      "The length of sentences",
      "The author's attitude toward the subject",
      "The number of paragraphs",
      "The vocabulary used",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "Context clues help a reader:",
    options: [
      "Write better essays",
      "Understand the meaning of unfamiliar words",
      "Memorize the passage",
      "Count the words in the text",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "Skimming a passage means:",
    options: [
      "Reading every word carefully",
      "Reading only the conclusion",
      "Quickly reading to get the general idea",
      "Looking for specific information",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "A supporting detail in a passage:",
    options: [
      "Contradicts the main idea",
      "Provides evidence or examples for the main idea",
      "States the author's name",
      "Introduces a new topic",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "What is the purpose of a topic sentence?",
    options: [
      "To end a paragraph",
      "To introduce the main idea of a paragraph",
      "To give an example",
      "To quote another author",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "Scanning a text is used to:",
    options: [
      "Read for general understanding",
      "Find specific information quickly",
      "Analyze the writing style",
      "Memorize the content",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "If a passage has a 'pessimistic' tone, the author feels:",
    options: ["Hopeful", "Neutral", "Negative or gloomy", "Excited"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "A summary of a passage should:",
    options: [
      "Include all minor details",
      "Be longer than the original",
      "Capture the main ideas in brief",
      "Copy sentences from the text",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "Which question tests literal comprehension?",
    options: [
      "Why do you think the character made that choice?",
      "What does the word 'benevolent' mean here?",
      "What did the character say in paragraph 2?",
      "How does this relate to your own life?",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "The author's purpose in a persuasive text is to:",
    options: ["Entertain", "Inform neutrally", "Convince the reader", "Tell a story"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "Which best defines a 'figurative language'?",
    options: [
      "Language that is literally true",
      "Language used to mean exactly what it says",
      "Non-literal language used for effect",
      "Technical or scientific language",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "A simile compares two things using:",
    options: ["metaphor", "'like' or 'as'", "personification", "hyperbole"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "Paraphrasing means:",
    options: [
      "Copying the text word for word",
      "Translating to another language",
      "Restating the text in your own words",
      "Skipping difficult parts",
    ],
    correctAnswer: 2,
    type: "practice",
  },

  // ============================================================
  // SUBJECT: Introduction to Programming
  // ============================================================

  // --- Topic: Basics of C++ / Programming Fundamentals ---
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "Which symbol is used to end a statement in C++?",
    options: [".", ":", ";", ","],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "Which of the following is a valid variable name in C++?",
    options: ["2name", "my-var", "_myVar", "class"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "What does 'cout' do in C++?",
    options: ["Takes input", "Outputs data to the console", "Declares a variable", "Ends the program"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "Which data type stores a single character in C++?",
    options: ["int", "float", "char", "string"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "What is the correct way to declare an integer variable named 'age'?",
    options: ["age = int;", "int age;", "integer age;", "var age = int;"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "Which header file is needed for 'cin' and 'cout' in C++?",
    options: ["<stdio.h>", "<math.h>", "<iostream>", "<string>"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "What is the output of: cout << 5 + 3;",
    options: ["5 + 3", "53", "8", "Error"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "A comment in C++ is written using:",
    options: ["/* */  or  //", "<!-- -->", "##", "''"],
    correctAnswer: 0,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "What does 'cin' do in C++?",
    options: ["Outputs to screen", "Reads input from the user", "Declares a variable", "Ends a loop"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "Which of the following is NOT a primitive data type in C++?",
    options: ["int", "float", "bool", "string"],
    correctAnswer: 3,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "What is the entry point function of a C++ program?",
    options: ["start()", "run()", "main()", "begin()"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "The '=' operator in C++ is used for:",
    options: ["Comparison", "Assignment", "Addition", "Boolean check"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "Which keyword is used to define a constant in C++?",
    options: ["static", "const", "final", "fixed"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "What is the modulus operator in C++?",
    options: ["/", "*", "%", "^"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "What does 'return 0;' at the end of main() indicate?",
    options: [
      "The program has an error",
      "The program ended unsuccessfully",
      "The program ended successfully",
      "The program should restart",
    ],
    correctAnswer: 2,
    type: "practice",
  },

  // --- Topic: Control Structures & Loops ---
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "Which loop is guaranteed to execute at least once?",
    options: ["for loop", "while loop", "do-while loop", "nested loop"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "What is the output of: for(int i=0; i<3; i++) cout << i;",
    options: ["123", "012", "0123", "321"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "Which statement exits a loop immediately?",
    options: ["continue", "return", "break", "exit"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "The 'continue' statement in a loop:",
    options: [
      "Terminates the loop",
      "Skips the rest of the current iteration and goes to the next",
      "Restarts the loop from beginning",
      "Exits the program",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "What will an infinite loop cause?",
    options: [
      "Compile error",
      "The program runs forever (or until manually stopped)",
      "Syntax error",
      "Variable overflow only",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "Which is the correct syntax for an if-else statement in C++?",
    options: [
      "if x > 0 { } else { }",
      "if (x > 0) { } else { }",
      "if [x > 0] { } else { }",
      "if x > 0 then { } else { }",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "A switch statement evaluates:",
    options: ["Boolean expressions", "A variable against multiple constant values", "Loops", "Functions"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "How many times will this loop run? for(int i=1; i<=5; i++)",
    options: ["4", "5", "6", "Infinite"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "What does the '==' operator do in a condition?",
    options: ["Assigns a value", "Checks equality", "Increments a value", "Declares a variable"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "Nested loops mean:",
    options: [
      "Two loops running in sequence",
      "A loop inside another loop",
      "A loop with a break statement",
      "A loop that skips iterations",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "Which operator represents logical AND in C++?",
    options: ["&", "||", "&&", "!"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "What is the default case in a switch statement used for?",
    options: [
      "It runs before all cases",
      "It handles values that don't match any case",
      "It exits the switch",
      "It declares variables",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "Which loop should you use when the number of iterations is known?",
    options: ["while", "do-while", "for", "switch"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "The condition in a while loop is checked:",
    options: [
      "After each iteration",
      "Before each iteration",
      "Only once at the start",
      "Only once at the end",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "What is the ternary operator syntax in C++?",
    options: [
      "condition ? value_if_true : value_if_false",
      "condition : value_if_true ? value_if_false",
      "if(condition) value_if_true else value_if_false",
      "condition || true : false",
    ],
    correctAnswer: 0,
    type: "practice",
  },

  // --- Topic: Functions & Arrays ---
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "A function in C++ is defined to:",
    options: [
      "Store data",
      "Perform a specific task that can be reused",
      "Declare variables",
      "Create loops",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "What is a function prototype?",
    options: [
      "The full definition of a function",
      "A declaration of the function before its definition",
      "A call to the function",
      "A return statement",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "How do you declare an integer array of size 5 in C++?",
    options: ["int arr[5];", "array int[5];", "int[5] arr;", "arr = int[5];"],
    correctAnswer: 0,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "Array indices in C++ start from:",
    options: ["1", "0", "-1", "Depends on the compiler"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "What does 'void' as a return type mean?",
    options: [
      "Returns an integer",
      "The function returns nothing",
      "The function has no parameters",
      "The function is recursive",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "What is the size of array: int arr[] = {1, 2, 3, 4, 5};",
    options: ["4", "5", "6", "Depends on compiler"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "Passing an argument by value means:",
    options: [
      "The original variable is changed",
      "A copy of the variable is passed to the function",
      "The function cannot use the variable",
      "The variable is deleted after the call",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "A recursive function is one that:",
    options: [
      "Has no return value",
      "Calls itself",
      "Takes no parameters",
      "Runs infinitely always",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "Which of the following accesses the 3rd element of array 'arr'?",
    options: ["arr[3]", "arr[2]", "arr(3)", "arr{3}"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "What happens if you access an out-of-bound array index in C++?",
    options: [
      "Compile error always",
      "Undefined behavior",
      "Returns 0 automatically",
      "Program prints an error and stops"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "Function overloading means:",
    options: [
      "A function that never returns",
      "Multiple functions with the same name but different parameters",
      "A function inside a loop",
      "A function that takes arrays only",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "Default parameters in a function are used when:",
    options: [
      "The function has no return type",
      "No argument is passed for that parameter",
      "The array is empty",
      "The function is recursive",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "Which of these is a correct function call: int result = add(3, 4);?",
    options: [
      "Only if add() returns void",
      "Yes, if add() returns int",
      "No, functions can't return values",
      "Only if 3 and 4 are declared as variables",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "A 2D array in C++ is used for:",
    options: [
      "Storing a single list of values",
      "Representing tables or matrices",
      "Defining functions",
      "Creating loops",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "The 'return' statement in a function:",
    options: [
      "Declares a variable",
      "Ends the function and optionally sends back a value",
      "Starts the function",
      "Calls another function",
    ],
    correctAnswer: 1,
    type: "practice",
  },

  // ============================================================
  // SUBJECT: Digital Logic Design (DLD)
  // ============================================================

  // --- Topic: Number Systems & Boolean Algebra ---
  {
    subject: "Digital Logic Design",
    topic: "Number Systems & Boolean Algebra",
    question: "What is the binary representation of decimal 10?",
    options: ["1010", "1100", "1001", "1110"],
    correctAnswer: 0,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Number Systems & Boolean Algebra",
    question: "Convert hexadecimal F to decimal:",
    options: ["14", "15", "16", "13"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Number Systems & Boolean Algebra",
    question: "The base of hexadecimal number system is:",
    options: ["2", "8", "10", "16"],
    correctAnswer: 3,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Number Systems & Boolean Algebra",
    question: "What is 1's complement of 1010?",
    options: ["0101", "1011", "0110", "1001"],
    correctAnswer: 0,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Number Systems & Boolean Algebra",
    question: "Boolean algebra is based on:",
    options: ["Decimal logic", "Two-valued logic (0 and 1)", "Hexadecimal logic", "Octal logic"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Number Systems & Boolean Algebra",
    question: "What is the result of: A + 0 = ?",
    options: ["0", "1", "A", "NOT A"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Number Systems & Boolean Algebra",
    question: "De Morgan's first theorem states: NOT(A + B) = ?",
    options: ["NOT A + NOT B", "NOT A . NOT B", "A . B", "NOT A + B"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Number Systems & Boolean Algebra",
    question: "Convert octal 17 to decimal:",
    options: ["15", "16", "17", "14"],
    correctAnswer: 0,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Number Systems & Boolean Algebra",
    question: "A . A' = ?",
    options: ["A", "1", "0", "A'"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Number Systems & Boolean Algebra",
    question: "2's complement is used to represent:",
    options: ["Positive numbers only", "Negative numbers in binary", "Fractions", "Hexadecimal numbers"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Number Systems & Boolean Algebra",
    question: "The octal number system has a base of:",
    options: ["2", "4", "8", "16"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Number Systems & Boolean Algebra",
    question: "What is the Boolean expression for XOR?",
    options: ["A.B", "A+B", "A⊕B = AB' + A'B", "A'B'"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Number Systems & Boolean Algebra",
    question: "The dual of A + 0 = A is:",
    options: ["A . 0 = A", "A . 1 = A", "A + 1 = 1", "A . 0 = 0"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Number Systems & Boolean Algebra",
    question: "Which of the following is equivalent to binary 1111?",
    options: ["Decimal 14", "Decimal 15", "Decimal 16", "Hex E"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Number Systems & Boolean Algebra",
    question: "The absorption law states: A + AB = ?",
    options: ["AB", "A", "B", "A + B"],
    correctAnswer: 1,
    type: "practice",
  },

  // --- Topic: Logic Gates & Combinational Circuits ---
  {
    subject: "Digital Logic Design",
    topic: "Logic Gates & Combinational Circuits",
    question: "Which gate outputs 1 only when all inputs are 1?",
    options: ["OR", "NOT", "AND", "NAND"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Logic Gates & Combinational Circuits",
    question: "The output of a NOT gate with input 0 is:",
    options: ["0", "1", "Undefined", "Depends on voltage"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Logic Gates & Combinational Circuits",
    question: "Which gate is called the 'universal gate'?",
    options: ["AND", "OR", "NAND", "XOR"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Logic Gates & Combinational Circuits",
    question: "The output of XOR gate when inputs are 1 and 1 is:",
    options: ["0", "1", "2", "Undefined"],
    correctAnswer: 0,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Logic Gates & Combinational Circuits",
    question: "A half adder adds how many bits?",
    options: ["1 bit", "2 bits (no carry-in)", "3 bits (with carry-in)", "4 bits"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Logic Gates & Combinational Circuits",
    question: "A multiplexer (MUX) is used to:",
    options: [
      "Add binary numbers",
      "Select one of many inputs based on select lines",
      "Store binary data",
      "Convert decimal to binary",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Logic Gates & Combinational Circuits",
    question: "A decoder with 3 input lines has how many output lines?",
    options: ["3", "6", "8", "16"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Logic Gates & Combinational Circuits",
    question: "The output of NOR gate is 1 when:",
    options: [
      "At least one input is 1",
      "All inputs are 0",
      "Both inputs are 1",
      "Only one input is 1",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Logic Gates & Combinational Circuits",
    question: "SOP stands for:",
    options: [
      "Sum of Products",
      "Sequence of Processes",
      "Sum of Processes",
      "Standard Output Protocol",
    ],
    correctAnswer: 0,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Logic Gates & Combinational Circuits",
    question: "A Karnaugh map (K-map) is used to:",
    options: [
      "Build flip-flops",
      "Simplify Boolean expressions",
      "Convert number systems",
      "Design multiplexers",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Logic Gates & Combinational Circuits",
    question: "An encoder does the opposite of a:",
    options: ["Multiplexer", "Decoder", "Flip-flop", "Register"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Logic Gates & Combinational Circuits",
    question: "A full adder differs from a half adder because it:",
    options: [
      "Has only one output",
      "Can add three bits (includes carry-in)",
      "Uses only AND gates",
      "Has no carry output",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Logic Gates & Combinational Circuits",
    question: "How many rows does a truth table with 3 inputs have?",
    options: ["3", "6", "8", "16"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Logic Gates & Combinational Circuits",
    question: "The XNOR gate output is 1 when:",
    options: [
      "Inputs are different",
      "All inputs are 0 only",
      "Inputs are the same",
      "At least one input is 1",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Logic Gates & Combinational Circuits",
    question: "POS stands for:",
    options: ["Product of Sums", "Parallel Output Signal", "Process of Sequences", "Pulse Output Signal"],
    correctAnswer: 0,
    type: "practice",
  },

  // --- Topic: Sequential Circuits & Flip-Flops ---
  {
    subject: "Digital Logic Design",
    topic: "Sequential Circuits & Flip-Flops",
    question: "Sequential circuits differ from combinational circuits because they have:",
    options: ["No gates", "Memory (they depend on past input)", "Only one input", "No output"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Sequential Circuits & Flip-Flops",
    question: "An SR flip-flop has an invalid state when:",
    options: ["S=0, R=0", "S=1, R=0", "S=0, R=1", "S=1, R=1"],
    correctAnswer: 3,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Sequential Circuits & Flip-Flops",
    question: "A D flip-flop stores the value of:",
    options: ["Its complement", "The Q output always", "The D input at the clock edge", "A constant 0"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Sequential Circuits & Flip-Flops",
    question: "A JK flip-flop with J=1 and K=1 will:",
    options: ["Set to 1", "Reset to 0", "Toggle its output", "Hold its current state"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Sequential Circuits & Flip-Flops",
    question: "A register is a group of:",
    options: ["Multiplexers", "Flip-flops used to store multi-bit data", "Logic gates", "Adders"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Sequential Circuits & Flip-Flops",
    question: "A counter counts in:",
    options: [
      "Only decimal",
      "A sequence of binary states",
      "Only hexadecimal",
      "Random order",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Sequential Circuits & Flip-Flops",
    question: "A synchronous circuit is one where:",
    options: [
      "All flip-flops change state with the clock",
      "There is no clock",
      "Flip-flops change at different times",
      "Inputs are analog",
    ],
    correctAnswer: 0,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Sequential Circuits & Flip-Flops",
    question: "A 3-bit binary ripple counter can count from:",
    options: ["0 to 5", "0 to 7", "1 to 8", "0 to 15"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Sequential Circuits & Flip-Flops",
    question: "The clock in a sequential circuit is used to:",
    options: [
      "Provide power",
      "Synchronize state changes",
      "Store binary data",
      "Amplify signals",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Sequential Circuits & Flip-Flops",
    question: "Which flip-flop is most commonly used in registers?",
    options: ["SR flip-flop", "JK flip-flop", "D flip-flop", "T flip-flop"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Sequential Circuits & Flip-Flops",
    question: "A T flip-flop toggles its output when T =",
    options: ["0", "1", "Always", "Never"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Sequential Circuits & Flip-Flops",
    question: "A Mealy machine output depends on:",
    options: [
      "Only current state",
      "Only inputs",
      "Both current state and inputs",
      "Only previous outputs",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Sequential Circuits & Flip-Flops",
    question: "A Moore machine output depends only on:",
    options: ["Inputs", "Current state", "Previous output", "Clock speed"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Sequential Circuits & Flip-Flops",
    question: "An asynchronous counter is also called:",
    options: ["Ring counter", "Ripple counter", "Johnson counter", "Decade counter"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Digital Logic Design",
    topic: "Sequential Circuits & Flip-Flops",
    question: "Preset and Clear inputs in a flip-flop are used to:",
    options: [
      "Initialize the flip-flop to a known state",
      "Change the clock frequency",
      "Add two binary numbers",
      "Decode outputs",
    ],
    correctAnswer: 0,
    type: "practice",
  },

  // ============================================================
  // SUBJECT: Data Structures
  // ============================================================

  // --- Topic: Arrays, Linked Lists & Stacks ---
  {
    subject: "Data Structures",
    topic: "Arrays, Linked Lists & Stacks",
    question: "Arrays store elements in:",
    options: ["Random memory locations", "Contiguous memory locations", "Linked nodes", "A tree structure"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Arrays, Linked Lists & Stacks",
    question: "The time complexity of accessing an element by index in an array is:",
    options: ["O(n)", "O(log n)", "O(1)", "O(n²)"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Arrays, Linked Lists & Stacks",
    question: "In a singly linked list, each node contains:",
    options: [
      "Data only",
      "Data and a pointer to the previous node",
      "Data and a pointer to the next node",
      "Two data fields",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Arrays, Linked Lists & Stacks",
    question: "A stack follows the principle of:",
    options: ["FIFO", "LIFO", "Random access", "Priority-based"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Arrays, Linked Lists & Stacks",
    question: "The operation to add an element to a stack is called:",
    options: ["Enqueue", "Push", "Insert", "Append"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Arrays, Linked Lists & Stacks",
    question: "The operation to remove an element from a stack is called:",
    options: ["Dequeue", "Delete", "Pop", "Remove"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Arrays, Linked Lists & Stacks",
    question: "Which data structure is best for implementing 'undo' functionality?",
    options: ["Queue", "Array", "Stack", "Linked list"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Arrays, Linked Lists & Stacks",
    question: "The disadvantage of arrays over linked lists is:",
    options: [
      "Slow access time",
      "Fixed size (static allocation)",
      "Elements are unordered",
      "No index-based access",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Arrays, Linked Lists & Stacks",
    question: "In a doubly linked list, each node has pointers to:",
    options: [
      "Next node only",
      "Previous node only",
      "Both next and previous nodes",
      "Head node only",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Arrays, Linked Lists & Stacks",
    question: "Stack overflow occurs when:",
    options: [
      "The stack is empty",
      "Too many pop operations are performed",
      "An element is pushed onto a full stack",
      "An element is inserted in the middle",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Arrays, Linked Lists & Stacks",
    question: "The head pointer in a linked list points to:",
    options: ["Last node", "Middle node", "First node", "Null"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Arrays, Linked Lists & Stacks",
    question: "Which of the following is NOT an advantage of linked lists over arrays?",
    options: [
      "Dynamic size",
      "Efficient insertion and deletion",
      "Faster random access",
      "No memory wastage",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Arrays, Linked Lists & Stacks",
    question: "A circular linked list is one where:",
    options: [
      "Every node points to itself",
      "The last node points to the first node",
      "There are no pointers",
      "Nodes are stored in a circle shape in memory",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Arrays, Linked Lists & Stacks",
    question: "What is the top of the stack?",
    options: [
      "The first element inserted",
      "The last element inserted (most recent)",
      "The middle element",
      "A fixed position",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Arrays, Linked Lists & Stacks",
    question: "The time complexity of inserting a node at the beginning of a linked list is:",
    options: ["O(n)", "O(log n)", "O(n²)", "O(1)"],
    correctAnswer: 3,
    type: "practice",
  },

  // --- Topic: Queues, Trees & Binary Search Trees ---
  {
    subject: "Data Structures",
    topic: "Queues, Trees & Binary Search Trees",
    question: "A queue follows the principle of:",
    options: ["LIFO", "FIFO", "Random order", "Priority only"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Queues, Trees & Binary Search Trees",
    question: "The operation to add an element to a queue is called:",
    options: ["Push", "Insert", "Enqueue", "Append"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Queues, Trees & Binary Search Trees",
    question: "In a Binary Search Tree (BST), the left subtree of a node contains:",
    options: [
      "Values greater than the node",
      "Values less than the node",
      "Equal values only",
      "Random values",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Queues, Trees & Binary Search Trees",
    question: "The root of a tree is:",
    options: ["The deepest node", "The topmost node with no parent", "A leaf node", "Any node"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Queues, Trees & Binary Search Trees",
    question: "A leaf node is a node that:",
    options: ["Has two children", "Has no children", "Is the root", "Has one child"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Queues, Trees & Binary Search Trees",
    question: "Inorder traversal of a BST gives elements in:",
    options: ["Random order", "Reverse sorted order", "Sorted (ascending) order", "Level order"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Queues, Trees & Binary Search Trees",
    question: "The height of a tree is:",
    options: [
      "The number of nodes in the tree",
      "The longest path from root to a leaf",
      "The number of leaf nodes",
      "The level of the root",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Queues, Trees & Binary Search Trees",
    question: "Which traversal visits: Left → Root → Right?",
    options: ["Preorder", "Postorder", "Inorder", "Level order"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Queues, Trees & Binary Search Trees",
    question: "A priority queue serves elements based on:",
    options: ["FIFO order", "LIFO order", "Their priority value", "Alphabetical order"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Queues, Trees & Binary Search Trees",
    question: "Searching in a balanced BST has time complexity:",
    options: ["O(n)", "O(n²)", "O(log n)", "O(1)"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Queues, Trees & Binary Search Trees",
    question: "A dequeue (deque) allows insertion and deletion from:",
    options: ["Front only", "Rear only", "Both front and rear", "Middle only"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Queues, Trees & Binary Search Trees",
    question: "The degree of a node in a tree is:",
    options: [
      "Its level in the tree",
      "The number of children it has",
      "The length of the path from root",
      "The height of its subtree",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Queues, Trees & Binary Search Trees",
    question: "Preorder traversal visits nodes in order:",
    options: [
      "Left → Right → Root",
      "Left → Root → Right",
      "Root → Left → Right",
      "Right → Root → Left",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Queues, Trees & Binary Search Trees",
    question: "Which data structure is used in BFS (Breadth-First Search)?",
    options: ["Stack", "Queue", "Tree", "Array"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Queues, Trees & Binary Search Trees",
    question: "A circular queue solves the problem of:",
    options: [
      "Slow searching",
      "Wasted space in a linear queue after dequeues",
      "Memory leaks",
      "Stack overflow",
    ],
    correctAnswer: 1,
    type: "practice",
  },

  // --- Topic: Sorting & Searching Algorithms ---
  {
    subject: "Data Structures",
    topic: "Sorting & Searching Algorithms",
    question: "What is the best-case time complexity of Bubble Sort?",
    options: ["O(n²)", "O(n log n)", "O(n)", "O(1)"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Sorting & Searching Algorithms",
    question: "Which sorting algorithm repeatedly selects the minimum element and places it in order?",
    options: ["Bubble Sort", "Insertion Sort", "Selection Sort", "Merge Sort"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Sorting & Searching Algorithms",
    question: "Binary search requires the array to be:",
    options: ["Random", "Sorted", "Unsorted", "Linked"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Sorting & Searching Algorithms",
    question: "The time complexity of binary search is:",
    options: ["O(n)", "O(n²)", "O(log n)", "O(1)"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Sorting & Searching Algorithms",
    question: "Merge sort uses the technique of:",
    options: [
      "Greedy approach",
      "Divide and conquer",
      "Dynamic programming",
      "Backtracking",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Sorting & Searching Algorithms",
    question: "The worst-case time complexity of Quick Sort is:",
    options: ["O(n log n)", "O(n)", "O(n²)", "O(log n)"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Sorting & Searching Algorithms",
    question: "Which sorting algorithm is best for nearly sorted data?",
    options: ["Selection Sort", "Merge Sort", "Insertion Sort", "Quick Sort"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Sorting & Searching Algorithms",
    question: "Linear search has time complexity:",
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Sorting & Searching Algorithms",
    question: "Which of these sorting algorithms is stable?",
    options: ["Selection Sort", "Quick Sort", "Merge Sort", "Heap Sort"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Sorting & Searching Algorithms",
    question: "Heap sort uses which data structure?",
    options: ["Stack", "Queue", "Linked list", "Heap (binary heap)"],
    correctAnswer: 3,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Sorting & Searching Algorithms",
    question: "Insertion sort works by:",
    options: [
      "Dividing the array into halves",
      "Inserting each element into its correct position in a sorted portion",
      "Swapping adjacent elements repeatedly",
      "Selecting the minimum each time",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Sorting & Searching Algorithms",
    question: "What is the average time complexity of Merge Sort?",
    options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Sorting & Searching Algorithms",
    question: "In Quick Sort, the 'pivot' is used to:",
    options: [
      "Merge two halves",
      "Partition the array into smaller and larger elements",
      "Find the minimum element",
      "Sort a subarray",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Sorting & Searching Algorithms",
    question: "Which search algorithm is used in unsorted arrays?",
    options: ["Binary Search", "Interpolation Search", "Linear Search", "Fibonacci Search"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Data Structures",
    topic: "Sorting & Searching Algorithms",
    question: "The space complexity of Merge Sort is:",
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"],
    correctAnswer: 2,
    type: "practice",
  },

  // ============================================================
  // SUBJECT: Calculus
  // ============================================================

  // --- Topic: Limits & Continuity ---
  {
    subject: "Calculus",
    topic: "Limits & Continuity",
    question: "What is lim(x→2) of (x² - 4)/(x - 2)?",
    options: ["0", "2", "4", "Undefined"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Limits & Continuity",
    question: "A function f(x) is continuous at x = a if:",
    options: [
      "f(a) is undefined",
      "lim(x→a) f(x) = f(a)",
      "The derivative at a is zero",
      "f(a) = 0",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Limits & Continuity",
    question: "What is lim(x→0) of sin(x)/x?",
    options: ["0", "∞", "1", "Undefined"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Limits & Continuity",
    question: "A left-hand limit is evaluated as x approaches a from:",
    options: ["The right side", "The left side (x < a)", "Both sides", "Infinity"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Limits & Continuity",
    question: "If lim(x→a⁺) f(x) ≠ lim(x→a⁻) f(x), then lim(x→a) f(x):",
    options: ["Is zero", "Does not exist", "Equals f(a)", "Is infinite"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Limits & Continuity",
    question: "What is lim(x→∞) of 1/x?",
    options: ["1", "∞", "0", "-1"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Limits & Continuity",
    question: "L'Hôpital's rule is applied when the limit gives:",
    options: ["Any value", "0/0 or ∞/∞ indeterminate form", "Always a zero", "A negative value"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Limits & Continuity",
    question: "A removable discontinuity occurs when:",
    options: [
      "The function has no value anywhere",
      "The limit exists but f(a) is undefined or not equal to the limit",
      "The limit does not exist",
      "The function is negative",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Limits & Continuity",
    question: "What is lim(x→3) of (x² - 9)/(x - 3)?",
    options: ["3", "6", "0", "9"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Limits & Continuity",
    question: "The Squeeze Theorem states that if g(x) ≤ f(x) ≤ h(x) and lim g = lim h = L, then:",
    options: [
      "lim f(x) does not exist",
      "lim f(x) = 0",
      "lim f(x) = L",
      "lim f(x) = g(x)",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Limits & Continuity",
    question: "An infinite discontinuity occurs when:",
    options: [
      "The limit equals zero",
      "The function approaches ±∞",
      "The function is constant",
      "The limit exists",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Limits & Continuity",
    question: "Which of the following functions is continuous everywhere?",
    options: ["f(x) = 1/x", "f(x) = tan(x)", "f(x) = x²", "f(x) = ln(x)"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Limits & Continuity",
    question: "What is lim(x→0) of (1 - cos x)/x?",
    options: ["1", "0", "∞", "1/2"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Limits & Continuity",
    question: "A jump discontinuity happens when:",
    options: [
      "The function is not defined",
      "The left and right limits exist but are not equal",
      "The limit equals infinity",
      "The function is periodic",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Limits & Continuity",
    question: "lim(x→∞) of (3x² + 2)/(x² + 1) = ?",
    options: ["0", "1", "2", "3"],
    correctAnswer: 3,
    type: "practice",
  },

  // --- Topic: Differentiation ---
  {
    subject: "Calculus",
    topic: "Differentiation",
    question: "The derivative of f(x) = x³ is:",
    options: ["x²", "3x²", "3x³", "x⁴/4"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Differentiation",
    question: "The derivative of a constant c is:",
    options: ["c", "1", "0", "c²"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Differentiation",
    question: "The chain rule is used to differentiate:",
    options: ["Sum of functions", "Product of functions", "Composite functions", "Quotients"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Differentiation",
    question: "What is d/dx [sin(x)]?",
    options: ["-sin(x)", "cos(x)", "-cos(x)", "tan(x)"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Differentiation",
    question: "The derivative of eˣ is:",
    options: ["xeˣ", "eˣ", "e^(x-1)", "1/eˣ"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Differentiation",
    question: "The product rule for u·v is:",
    options: ["u'·v'", "u'v + uv'", "u'v - uv'", "(u + v)'"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Differentiation",
    question: "A critical point of f(x) occurs where:",
    options: ["f(x) = 0", "f'(x) = 0 or undefined", "f''(x) = 0", "x = 0"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Differentiation",
    question: "If f'(x) > 0, the function is:",
    options: ["Decreasing", "Constant", "Increasing", "At a maximum"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Differentiation",
    question: "What is d/dx [ln(x)]?",
    options: ["ln(x)", "1/x", "x", "eˣ"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Differentiation",
    question: "Implicit differentiation is used when:",
    options: [
      "y is explicitly given in terms of x",
      "The function is a constant",
      "y cannot be easily isolated from the equation",
      "The function is linear",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Differentiation",
    question: "The second derivative f''(x) gives information about:",
    options: ["Slope of the function", "Concavity of the function", "Area under the curve", "Limits"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Differentiation",
    question: "What is d/dx [cos(x)]?",
    options: ["sin(x)", "cos(x)", "-sin(x)", "-cos(x)"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Differentiation",
    question: "The derivative of f(x) = xⁿ is:",
    options: ["nxⁿ", "nxⁿ⁻¹", "xⁿ⁻¹", "n·x"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Differentiation",
    question: "A point of inflection is where:",
    options: [
      "f(x) = 0",
      "f'(x) = 0",
      "The concavity changes (f''(x) changes sign)",
      "The function is maximum",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Differentiation",
    question: "The quotient rule for u/v is:",
    options: [
      "(u'v + uv') / v²",
      "(u'v - uv') / v²",
      "u'/ v'",
      "(u - v)' / v",
    ],
    correctAnswer: 1,
    type: "practice",
  },

  // --- Topic: Integration ---
  {
    subject: "Calculus",
    topic: "Integration",
    question: "Integration is the reverse process of:",
    options: ["Limits", "Differentiation", "Continuity", "Algebraic simplification"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Integration",
    question: "∫xⁿ dx = ?",
    options: ["nxⁿ⁻¹ + C", "xⁿ⁺¹/(n+1) + C", "xⁿ + C", "n·xⁿ + C"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Integration",
    question: "∫eˣ dx = ?",
    options: ["xeˣ + C", "eˣ + C", "eˣ/x + C", "e^(x+1) + C"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Integration",
    question: "A definite integral gives:",
    options: [
      "A function",
      "A numerical value (area under the curve between two limits)",
      "A derivative",
      "A limit",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Integration",
    question: "∫cos(x) dx = ?",
    options: ["-sin(x) + C", "sin(x) + C", "-cos(x) + C", "tan(x) + C"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Integration",
    question: "The constant 'C' in indefinite integration represents:",
    options: [
      "A specific constant value",
      "The constant of integration (any constant)",
      "The initial condition",
      "A coefficient",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Integration",
    question: "The Fundamental Theorem of Calculus connects:",
    options: [
      "Limits and continuity",
      "Differentiation and integration",
      "Algebra and geometry",
      "Series and sequences",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Integration",
    question: "∫(1/x) dx = ?",
    options: ["1/x² + C", "ln|x| + C", "x + C", "-1/x² + C"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Integration",
    question: "The technique of u-substitution is analogous to:",
    options: ["Product rule", "Quotient rule", "Chain rule", "Power rule"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Integration",
    question: "∫sin(x) dx = ?",
    options: ["cos(x) + C", "-cos(x) + C", "sin(x) + C", "-sin(x) + C"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Integration",
    question: "A definite integral ∫[a to b] f(x)dx = F(b) - F(a) is evaluated using:",
    options: [
      "L'Hôpital's Rule",
      "The Fundamental Theorem of Calculus Part 2",
      "The Squeeze Theorem",
      "Taylor Series",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Integration",
    question: "Integration by parts uses the formula:",
    options: [
      "∫uv dx = uv' - u'v",
      "∫u dv = uv - ∫v du",
      "∫u dv = u + v",
      "∫uv dx = u'v'",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Integration",
    question: "What is ∫₀² x dx?",
    options: ["1", "2", "4", "0"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Integration",
    question: "An improper integral is one where:",
    options: [
      "The integrand is negative",
      "The limits of integration are infinite or the integrand is unbounded",
      "The function has no antiderivative",
      "The constant C is missing",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Calculus",
    topic: "Integration",
    question: "∫ k dx (where k is a constant) = ?",
    options: ["k²x + C", "kx + C", "0 + C", "k/x + C"],
    correctAnswer: 1,
    type: "practice",
  },
];

// ============================================================
// SEED FUNCTION
// ============================================================
const seedPracticeQuestions = async () => {
  try {
    await connectDB();

    // Remove existing practice questions to avoid duplicates
    await Question.deleteMany({ type: "practice" });
    console.log("🗑️ Cleared old practice questions");

    await Question.insertMany(practiceQuestions);
    console.log(`✅ Seeded ${practiceQuestions.length} practice questions successfully!`);

    // Summary
    const subjects = [...new Set(practiceQuestions.map(q => q.subject))];
    subjects.forEach(sub => {
      const count = practiceQuestions.filter(q => q.subject === sub).length;
      console.log(`  📚 ${sub}: ${count} questions`);
    });

    process.exit(0);
  } catch (error) {
    console.error("❌ Seeding failed:", error);
    process.exit(1);
  }
};

seedPracticeQuestions();
