module.exports = [

  // ============================================================
  // SUBJECT: English
  // ============================================================

  // --- Topic: Grammar & Parts of Speech ---
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Which of the following is a proper noun?",
    options: ["city", "river", "London", "mountain"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Identify the verb in the sentence: 'She quickly ran to the store.'",
    options: ["She", "quickly", "ran", "store"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Which sentence is grammatically correct?",
    options: [
      "He don't know the answer.",
      "She doesn't knows the answer.",
      "They doesn't know the answer.",
      "He doesn't know the answer.",
    ],
    correctAnswer: 3,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "What part of speech is the word 'beautiful' in 'She wore a beautiful dress'?",
    options: ["Noun", "Adverb", "Adjective", "Verb"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Which word is an adverb in: 'He spoke loudly in the hall'?",
    options: ["He", "spoke", "loudly", "hall"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "A pronoun is used to:",
    options: [
      "Describe a noun",
      "Replace a noun",
      "Connect two clauses",
      "Express action",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Which is a collective noun?",
    options: ["Happiness", "Flock", "Running", "Beautiful"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "What type of sentence is: 'Close the door!'?",
    options: ["Declarative", "Interrogative", "Exclamatory", "Imperative"],
    correctAnswer: 3,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Which conjunction is used to show contrast?",
    options: ["and", "because", "but", "so"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "The plural of 'child' is:",
    options: ["childs", "childes", "children", "childrens"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Which article is used before a vowel sound?",
    options: ["a", "an", "the", "both a and the"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "In 'The cat sat on the mat', the preposition is:",
    options: ["The", "cat", "sat", "on"],
    correctAnswer: 3,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Which sentence uses the past perfect tense?",
    options: [
      "She is eating.",
      "She had eaten before he arrived.",
      "She ate lunch.",
      "She will eat later.",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "An interjection expresses:",
    options: ["Action", "Description", "Strong emotion", "Relation between nouns"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Grammar & Parts of Speech",
    question: "Which sentence is in passive voice?",
    options: [
      "Ali wrote the letter.",
      "The letter was written by Ali.",
      "Ali is writing the letter.",
      "Ali had written the letter.",
    ],
    correctAnswer: 1,
    type: "practice",
  },

  // --- Topic: Essay Writing & Composition ---
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "What is the main purpose of an introductory paragraph in an essay?",
    options: [
      "To provide evidence",
      "To summarize the essay",
      "To present the thesis and hook the reader",
      "To list all arguments",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "A thesis statement is best described as:",
    options: [
      "A question about the topic",
      "The central argument of the essay",
      "A list of facts",
      "The conclusion of the essay",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "Which paragraph type presents facts to support the main argument?",
    options: ["Introduction", "Body paragraph", "Conclusion", "Hook paragraph"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "What does 'coherence' mean in essay writing?",
    options: [
      "Using difficult vocabulary",
      "Ideas flowing logically and smoothly",
      "Writing long sentences",
      "Using many examples",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "A persuasive essay aims to:",
    options: [
      "Entertain the reader",
      "Describe a place",
      "Convince the reader of a viewpoint",
      "Narrate a story",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "Which transitional phrase introduces a contrasting idea?",
    options: ["Furthermore", "In addition", "However", "As a result"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "The concluding paragraph of an essay should:",
    options: [
      "Introduce a new argument",
      "Restate the thesis and summarize key points",
      "Ask a question",
      "List all the evidence used",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "Which essay type tells about personal experience?",
    options: ["Argumentative", "Expository", "Narrative", "Descriptive"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "Plagiarism in academic writing means:",
    options: [
      "Writing too many paragraphs",
      "Using someone else's work without credit",
      "Writing in a formal tone",
      "Using transitional phrases",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "Which of these is NOT a prewriting strategy?",
    options: ["Brainstorming", "Outlining", "Proofreading", "Mind mapping"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "The audience in writing refers to:",
    options: [
      "The writer's purpose",
      "The people who will read the writing",
      "The topic of the essay",
      "The length of the essay",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "In formal academic writing, contractions like 'don't' should be:",
    options: ["Used frequently", "Used only in conclusions", "Avoided", "Used in introductions only"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "A 'hook' in the introduction is meant to:",
    options: [
      "Define the topic",
      "List evidence",
      "Grab the reader's attention",
      "State the conclusion",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "Revising an essay involves:",
    options: [
      "Checking spelling errors only",
      "Improving content, structure, and clarity",
      "Adding more words to meet word count",
      "Writing a new essay",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Essay Writing & Composition",
    question: "An expository essay is written to:",
    options: [
      "Argue a position",
      "Tell a story",
      "Explain or inform about a topic",
      "Describe feelings",
    ],
    correctAnswer: 2,
    type: "practice",
  },

  // --- Topic: Reading Comprehension ---
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "The main idea of a passage is:",
    options: [
      "A minor detail in the text",
      "The central point the author wants to convey",
      "The first sentence of the paragraph",
      "A supporting example",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "Inference in reading means:",
    options: [
      "Reading the text aloud",
      "Finding a word in the dictionary",
      "Drawing a conclusion not directly stated",
      "Summarizing the passage",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "The tone of a passage refers to:",
    options: [
      "The length of sentences",
      "The author's attitude toward the subject",
      "The number of paragraphs",
      "The vocabulary used",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "Context clues help a reader:",
    options: [
      "Write better essays",
      "Understand the meaning of unfamiliar words",
      "Memorize the passage",
      "Count the words in the text",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "Skimming a passage means:",
    options: [
      "Reading every word carefully",
      "Reading only the conclusion",
      "Quickly reading to get the general idea",
      "Looking for specific information",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "A supporting detail in a passage:",
    options: [
      "Contradicts the main idea",
      "Provides evidence or examples for the main idea",
      "States the author's name",
      "Introduces a new topic",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "What is the purpose of a topic sentence?",
    options: [
      "To end a paragraph",
      "To introduce the main idea of a paragraph",
      "To give an example",
      "To quote another author",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "Scanning a text is used to:",
    options: [
      "Read for general understanding",
      "Find specific information quickly",
      "Analyze the writing style",
      "Memorize the content",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "If a passage has a 'pessimistic' tone, the author feels:",
    options: ["Hopeful", "Neutral", "Negative or gloomy", "Excited"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "A summary of a passage should:",
    options: [
      "Include all minor details",
      "Be longer than the original",
      "Capture the main ideas in brief",
      "Copy sentences from the text",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "Which question tests literal comprehension?",
    options: [
      "Why do you think the character made that choice?",
      "What does the word 'benevolent' mean here?",
      "What did the character say in paragraph 2?",
      "How does this relate to your own life?",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "The author's purpose in a persuasive text is to:",
    options: ["Entertain", "Inform neutrally", "Convince the reader", "Tell a story"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "Which best defines a 'figurative language'?",
    options: [
      "Language that is literally true",
      "Language used to mean exactly what it says",
      "Non-literal language used for effect",
      "Technical or scientific language",
    ],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "A simile compares two things using:",
    options: ["metaphor", "'like' or 'as'", "personification", "hyperbole"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "English",
    topic: "Reading Comprehension",
    question: "Paraphrasing means:",
    options: [
      "Copying the text word for word",
      "Translating to another language",
      "Restating the text in your own words",
      "Skipping difficult parts",
    ],
    correctAnswer: 2,
    type: "practice",
  },

  // ============================================================
  // SUBJECT: Introduction to Programming
  // ============================================================

  // --- Topic: Basics of C++ / Programming Fundamentals ---
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "Which symbol is used to end a statement in C++?",
    options: [".", ":", ";", ","],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "Which of the following is a valid variable name in C++?",
    options: ["2name", "my-var", "_myVar", "class"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "What does 'cout' do in C++?",
    options: ["Takes input", "Outputs data to the console", "Declares a variable", "Ends the program"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "Which data type stores a single character in C++?",
    options: ["int", "float", "char", "string"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "What is the correct way to declare an integer variable named 'age'?",
    options: ["age = int;", "int age;", "integer age;", "var age = int;"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "Which header file is needed for 'cin' and 'cout' in C++?",
    options: ["<stdio.h>", "<math.h>", "<iostream>", "<string>"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "What is the output of: cout << 5 + 3;",
    options: ["5 + 3", "53", "8", "Error"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "A comment in C++ is written using:",
    options: ["/* */  or  //", "<!-- -->", "##", "''"],
    correctAnswer: 0,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "What does 'cin' do in C++?",
    options: ["Outputs to screen", "Reads input from the user", "Declares a variable", "Ends a loop"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "Which of the following is NOT a primitive data type in C++?",
    options: ["int", "float", "bool", "string"],
    correctAnswer: 3,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "What is the entry point function of a C++ program?",
    options: ["start()", "run()", "main()", "begin()"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "The '=' operator in C++ is used for:",
    options: ["Comparison", "Assignment", "Addition", "Boolean check"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "Which keyword is used to define a constant in C++?",
    options: ["static", "const", "final", "fixed"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "What is the modulus operator in C++?",
    options: ["/", "*", "%", "^"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Basics of C++ / Programming Fundamentals",
    question: "What does 'return 0;' at the end of main() indicate?",
    options: [
      "The program has an error",
      "The program ended unsuccessfully",
      "The program ended successfully",
      "The program should restart",
    ],
    correctAnswer: 2,
    type: "practice",
  },

  // --- Topic: Control Structures & Loops ---
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "Which loop is guaranteed to execute at least once?",
    options: ["for loop", "while loop", "do-while loop", "nested loop"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "What is the output of: for(int i=0; i<3; i++) cout << i;",
    options: ["123", "012", "0123", "321"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "Which statement exits a loop immediately?",
    options: ["continue", "return", "break", "exit"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "The 'continue' statement in a loop:",
    options: [
      "Terminates the loop",
      "Skips the rest of the current iteration and goes to the next",
      "Restarts the loop from beginning",
      "Exits the program",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "What will an infinite loop cause?",
    options: [
      "Compile error",
      "The program runs forever (or until manually stopped)",
      "Syntax error",
      "Variable overflow only",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "Which is the correct syntax for an if-else statement in C++?",
    options: [
      "if x > 0 { } else { }",
      "if (x > 0) { } else { }",
      "if [x > 0] { } else { }",
      "if x > 0 then { } else { }",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "A switch statement evaluates:",
    options: ["Boolean expressions", "A variable against multiple constant values", "Loops", "Functions"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "How many times will this loop run? for(int i=1; i<=5; i++)",
    options: ["4", "5", "6", "Infinite"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "What does the '==' operator do in a condition?",
    options: ["Assigns a value", "Checks equality", "Increments a value", "Declares a variable"],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "Nested loops mean:",
    options: [
      "Two loops running in sequence",
      "A loop inside another loop",
      "A loop with a break statement",
      "A loop that skips iterations",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "Which operator represents logical AND in C++?",
    options: ["&", "||", "&&", "!"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "What is the default case in a switch statement used for?",
    options: [
      "It runs before all cases",
      "It handles values that don't match any case",
      "It exits the switch",
      "It declares variables",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "Which loop should you use when the number of iterations is known?",
    options: ["while", "do-while", "for", "switch"],
    correctAnswer: 2,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "The condition in a while loop is checked:",
    options: [
      "After each iteration",
      "Before each iteration",
      "Only once at the start",
      "Only once at the end",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Control Structures & Loops",
    question: "What is the ternary operator syntax in C++?",
    options: [
      "condition ? value_if_true : value_if_false",
      "condition : value_if_true ? value_if_false",
      "if(condition) value_if_true else value_if_false",
      "condition || true : false",
    ],
    correctAnswer: 0,
    type: "practice",
  },

  // --- Topic: Functions & Arrays ---
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "A function in C++ is defined to:",
    options: [
      "Store data",
      "Perform a specific task that can be reused",
      "Declare variables",
      "Create loops",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "What is a function prototype?",
    options: [
      "The full definition of a function",
      "A declaration of the function before its definition",
      "A call to the function",
      "A return statement",
    ],
    correctAnswer: 1,
    type: "practice",
  },
  {
    subject: "Introduction to Programming",
    topic: "Functions & Arrays",
    question: "How do you declare an integer array of size 5 in C++?",
    options: ["int arr[5];